name: API Contract Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Validate OpenAPI documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: "infra/apis/bets-api.yaml"
          spectral_ruleset: "infra/rules/openapi3.spectral.yaml"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          event_name: ${{ github.event_name }}

  contract:
    name: Check API contract
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
